######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 7 09:51:01 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += IDrawableObject.hpp mainwindow.h mapitem.h rtypeitem.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp mapitem.cpp rtypeitem.cpp
